#!/usr/bin/env python3
"""
PTO2 Scheduling Report Generator (tensormap_and_ringbuffer)

Inputs:
  - outputs/perf_swimlane_*.json (generated by --enable-profiling)
  - Optional log file that contains lines printed by AICPU scheduler:
      PTO2_SCHED_PROFILE_JSON {...}

Outputs:
  - outputs/pto2_schedule_report_<timestamp>.md

This report focuses on "scheduling overhead" vs "kernel execution time",
and explains the ordered scheduler phases for tensormap_and_ringbuffer.
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


def _find_latest_outputs_file(pattern: str) -> Path:
    outputs_dir = Path("outputs")
    files = sorted(outputs_dir.glob(pattern))
    if not files:
        raise FileNotFoundError(f"no files matched outputs/{pattern}")
    return max(files, key=lambda p: p.stat().st_mtime)


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _load_kernel_config_mapping(config_path: Optional[Path]) -> Dict[int, str]:
    if config_path is None:
        return {}
    if not config_path.exists():
        raise FileNotFoundError(str(config_path))

    import importlib.util

    spec = importlib.util.spec_from_file_location("kernel_config", config_path)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot import kernel_config from {config_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    mapping: Dict[int, str] = {}
    kernels = getattr(module, "KERNELS", None)
    if not isinstance(kernels, list):
        return mapping
    for k in kernels:
        try:
            func_id = int(k.get("func_id"))
        except Exception:
            continue
        name = k.get("name")
        if isinstance(name, str) and name:
            mapping[func_id] = name
    return mapping


def _percentile(sorted_vals: List[float], p: float) -> float:
    if not sorted_vals:
        return 0.0
    if p <= 0:
        return float(sorted_vals[0])
    if p >= 100:
        return float(sorted_vals[-1])
    k = (len(sorted_vals) - 1) * (p / 100.0)
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return float(sorted_vals[int(k)])
    d0 = sorted_vals[f] * (c - k)
    d1 = sorted_vals[c] * (k - f)
    return float(d0 + d1)


@dataclass(frozen=True)
class TaskTiming:
    task_id: int
    func_id: int
    core_id: int
    core_type: str
    exec_us: float
    dispatch_us: Optional[float]
    start_us: float
    end_us: float
    finish_us: Optional[float]

    @property
    def head_overhead_us(self) -> Optional[float]:
        if self.dispatch_us is None:
            return None
        return self.start_us - self.dispatch_us

    @property
    def tail_overhead_us(self) -> Optional[float]:
        if self.finish_us is None:
            return None
        return self.finish_us - self.end_us

    @property
    def schedule_us(self) -> Optional[float]:
        if self.dispatch_us is None or self.finish_us is None:
            return None
        return self.finish_us - self.dispatch_us


def _parse_tasks(perf: Dict[str, Any]) -> List[TaskTiming]:
    tasks = perf.get("tasks")
    if not isinstance(tasks, list):
        raise ValueError("invalid perf_swimlane json: missing tasks[]")

    out: List[TaskTiming] = []
    for t in tasks:
        try:
            task_id = int(t["task_id"])
            func_id = int(t["func_id"])
            core_id = int(t["core_id"])
            core_type = str(t.get("core_type", ""))
            exec_us = float(t["duration_us"])
            start_us = float(t["start_time_us"])
            end_us = float(t["end_time_us"])
        except Exception:
            continue

        dispatch_us = None
        finish_us = None
        if "dispatch_time_us" in t and "finish_time_us" in t:
            du = float(t["dispatch_time_us"])
            fu = float(t["finish_time_us"])
            # 0.0 means "not recorded"
            dispatch_us = du if du > 0 else None
            finish_us = fu if fu > 0 else None

        out.append(
            TaskTiming(
                task_id=task_id,
                func_id=func_id,
                core_id=core_id,
                core_type=core_type,
                exec_us=exec_us,
                dispatch_us=dispatch_us,
                start_us=start_us,
                end_us=end_us,
                finish_us=finish_us,
            )
        )
    out.sort(key=lambda x: x.task_id)
    return out


def _fmt_us(x: Optional[float]) -> str:
    if x is None:
        return "n/a"
    return f"{x:.3f}"


def _stats(values: List[float]) -> Dict[str, float]:
    if not values:
        return {"count": 0}
    s = sorted(values)
    return {
        "count": float(len(values)),
        "mean": statistics.fmean(values),
        "p50": _percentile(s, 50),
        "p90": _percentile(s, 90),
        "p99": _percentile(s, 99),
        "min": s[0],
        "max": s[-1],
    }


def _phase_ranking_row(name: str, us: float, total_us: float) -> str:
    pct = (us * 100.0 / total_us) if total_us > 0 else 0.0
    return f"| {name} | {us:.3f} | {pct:.1f}% |"


def _parse_scheduler_profile_json_lines(log_path: Path) -> List[Dict[str, Any]]:
    profiles: List[Tuple[int, Dict[str, Any]]] = []
    with log_path.open("r", encoding="utf-8", errors="replace") as f:
        for lineno, line in enumerate(f, 1):
            marker = "PTO2_SCHED_PROFILE_JSON "
            idx = line.find(marker)
            if idx < 0:
                continue
            payload = line[idx + len(marker):].strip()
            try:
                profiles.append((lineno, json.loads(payload)))
            except Exception:
                continue
    # Drop line numbers by default (caller may re-filter).
    return [p for _, p in profiles]


def _parse_scheduler_profiles_with_lineno(log_path: Path) -> List[Tuple[int, Dict[str, Any]]]:
    out: List[Tuple[int, Dict[str, Any]]] = []
    with log_path.open("r", encoding="utf-8", errors="replace") as f:
        for lineno, line in enumerate(f, 1):
            marker = "PTO2_SCHED_PROFILE_JSON "
            idx = line.find(marker)
            if idx < 0:
                continue
            payload = line[idx + len(marker):].strip()
            try:
                out.append((lineno, json.loads(payload)))
            except Exception:
                continue
    return out


def _pick_last_run_profiles(
    profiles_with_lineno: List[Tuple[int, Dict[str, Any]]],
    log_path: Path,
    perf_filename: str,
) -> List[Dict[str, Any]]:
    if not profiles_with_lineno:
        return []

    # Prefer selecting the profiles closest to the run that produced `perf_filename`.
    target_line: Optional[int] = None
    try:
        with log_path.open("r", encoding="utf-8", errors="replace") as f:
            for lineno, line in enumerate(f, 1):
                if perf_filename in line:
                    target_line = lineno
    except Exception:
        target_line = None

    candidates = profiles_with_lineno
    if target_line is not None:
        candidates = [(ln, p) for (ln, p) in profiles_with_lineno if ln < target_line]

    # Walk backwards: take one profile per thread_idx; stop once thread_idx repeats (previous run).
    selected: List[Dict[str, Any]] = []
    seen_threads: set[int] = set()
    for _, p in reversed(candidates):
        tid = int(p.get("thread_idx", -1))
        if tid in seen_threads:
            break
        seen_threads.add(tid)
        selected.append(p)

    if not selected:
        return []
    return list(reversed(selected))


def _sum_profiles(profiles: List[Dict[str, Any]]) -> Dict[str, Any]:
    keys_sum = ["total_us", "scan_us", "orch_drain_us", "complete_us", "dispatch_us", "yield_us"]
    keys_int = [
        "loops",
        "yield_calls",
        "completed_by_thread",
        "fanout_total_traversed",
        "perf_ts_update_ok",
        "perf_ts_update_fail",
    ]
    out: Dict[str, Any] = {"threads": len(profiles)}
    for k in keys_sum:
        out[k] = sum(float(p.get(k, 0.0)) for p in profiles)
    for k in keys_int:
        out[k] = sum(int(p.get(k, 0)) for p in profiles)
    out["fanout_max_len"] = max((int(p.get("fanout_max_len", 0)) for p in profiles), default=0)
    out["task_count_final"] = max((int(p.get("task_count_final", 0)) for p in profiles), default=0)
    out["completed_final"] = max((int(p.get("completed_final", 0)) for p in profiles), default=0)
    return out


def _func_name(func_id: int, mapping: Dict[int, str]) -> str:
    return mapping.get(func_id, f"Func_{func_id}")


def _write_report(
    out_path: Path,
    perf_path: Path,
    tasks: List[TaskTiming],
    func_map: Dict[int, str],
    log_path: Optional[Path],
    sched_profiles: List[Dict[str, Any]],
) -> None:
    total_tasks = len(tasks)
    exec_us_all = [t.exec_us for t in tasks]

    sched_us_all = [x for x in (t.schedule_us for t in tasks) if x is not None]
    head_us_all = [x for x in (t.head_overhead_us for t in tasks) if x is not None]
    tail_us_all = [x for x in (t.tail_overhead_us for t in tasks) if x is not None]
    # Component sums (for accurate share)
    exec_us_sum = sum(exec_us_all)
    head_us_sum = sum(head_us_all)
    tail_us_sum = sum(tail_us_all)
    sched_us_sum = sum(sched_us_all)

    exec_stats = _stats(exec_us_all)
    sched_stats = _stats(sched_us_all)
    head_stats = _stats(head_us_all)
    tail_stats = _stats(tail_us_all)

    earliest_dispatch = min((t.dispatch_us for t in tasks if t.dispatch_us is not None), default=None)
    latest_finish = max((t.finish_us for t in tasks if t.finish_us is not None), default=None)
    total_span_us = None
    if earliest_dispatch is not None and latest_finish is not None:
        total_span_us = latest_finish - earliest_dispatch

    # Per-func schedule/exec
    per_func: Dict[int, Dict[str, List[float]]] = {}
    for t in tasks:
        per_func.setdefault(t.func_id, {"exec": [], "sched": [], "head": [], "tail": []})
        per_func[t.func_id]["exec"].append(t.exec_us)
        if t.schedule_us is not None:
            per_func[t.func_id]["sched"].append(t.schedule_us)
        if t.head_overhead_us is not None:
            per_func[t.func_id]["head"].append(t.head_overhead_us)
        if t.tail_overhead_us is not None:
            per_func[t.func_id]["tail"].append(t.tail_overhead_us)

    # Outliers (schedule_us)
    outliers = sorted(
        (t for t in tasks if t.schedule_us is not None),
        key=lambda x: x.schedule_us or 0.0,
        reverse=True,
    )[:20]

    # Scheduler profiles
    sched_sum = _sum_profiles(sched_profiles) if sched_profiles else None

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# PTO2 调度 Profiling 报告（tensormap_and_ringbuffer）\n\n")
        f.write(f"- 生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"- perf 文件: {perf_path}\n")
        if log_path is not None:
            f.write(f"- log 文件: {log_path}\n")
        f.write("\n")

        f.write("## 1) 概览\n\n")
        f.write(f"- 任务数: {total_tasks}\n")
        f.write(f"- 任务执行时间（duration_us）: mean={exec_stats.get('mean', 0.0):.3f}us, "
                f"p50={exec_stats.get('p50', 0.0):.3f}us, p90={exec_stats.get('p90', 0.0):.3f}us, "
                f"p99={exec_stats.get('p99', 0.0):.3f}us\n")
        if sched_us_all:
            f.write(f"- 调度窗口时间（finish-dispatch）: mean={sched_stats.get('mean', 0.0):.3f}us, "
                    f"p50={sched_stats.get('p50', 0.0):.3f}us, p90={sched_stats.get('p90', 0.0):.3f}us, "
                    f"p99={sched_stats.get('p99', 0.0):.3f}us\n")
            f.write(f"- Head 开销（start-dispatch）: mean={head_stats.get('mean', 0.0):.3f}us\n")
            f.write(f"- Tail 开销（finish-end）: mean={tail_stats.get('mean', 0.0):.3f}us\n")
            if total_span_us is not None:
                f.write(f"- 全局跨度（latest_finish - earliest_dispatch）: {total_span_us:.3f}us\n")
            if sched_us_sum > 0:
                f.write("\n### 调度窗口分解（按顺序）\n\n")
                f.write("调度窗口（`finish-dispatch`）可分解为 3 段：\n\n")
                f.write("1. `dispatch → start`：Head（派发到核开始执行）\n")
                f.write("2. `start → end`：Exec（核上执行）\n")
                f.write("3. `end → finish`：Tail（核结束到 AICPU 观测完成）\n\n")

                parts = [
                    ("tail (end→finish)", tail_us_sum),
                    ("exec (start→end)", exec_us_sum),
                    ("head (dispatch→start)", head_us_sum),
                ]
                parts.sort(key=lambda x: x[1], reverse=True)
                f.write("| part | sum(us) | share |\n")
                f.write("|---|---:|---:|\n")
                for name, us in parts:
                    pct = us * 100.0 / sched_us_sum if sched_us_sum > 0 else 0.0
                    f.write(f"| {name} | {us:.3f} | {pct:.1f}% |\n")
                f.write("\n")
        else:
            f.write("- 调度窗口时间: n/a（perf_swimlane 中缺少 dispatch/finish 时间戳）\n")
        f.write("\n")

        f.write("## 2) 调度/执行对比（按 func_id）\n\n")
        f.write("| func_id | name | count | exec_mean(us) | sched_mean(us) | head_mean(us) | tail_mean(us) |\n")
        f.write("|---:|---|---:|---:|---:|---:|---:|\n")
        for func_id in sorted(per_func.keys()):
            data = per_func[func_id]
            exec_m = statistics.fmean(data["exec"]) if data["exec"] else 0.0
            sched_m = statistics.fmean(data["sched"]) if data["sched"] else None
            head_m = statistics.fmean(data["head"]) if data["head"] else None
            tail_m = statistics.fmean(data["tail"]) if data["tail"] else None
            f.write(
                f"| {func_id} | {_func_name(func_id, func_map)} | {len(data['exec'])} | {exec_m:.3f} | "
                f"{_fmt_us(sched_m)} | {_fmt_us(head_m)} | {_fmt_us(tail_m)} |\n"
            )
        f.write("\n")

        f.write("## 3) 调度循环耗时（AICPU scheduler）\n\n")
        f.write("调度循环按顺序包含这些阶段（tensormap_and_ringbuffer）：\n\n")
        f.write("1. `scan`：增量扫描新提交任务（`current_task_index`），发现 `fanin_count==0` 的 root tasks 并入队\n")
        f.write("2. `orch_drain`：从 orchestrator 的 ready queue 中 drain 早就绪任务并入队\n")
        f.write("3. `complete`：轮询各 core 状态，处理完成任务：标记完成、遍历 fanout、更新 fanin_refcount、消费者入队\n")
        f.write("4. `dispatch`：从 ready queue 取任务，构建 payload，写寄存器派发到空闲 core\n")
        f.write("5. `yield`：本轮无进展时让出 CPU（空转等待）\n\n")

        if not sched_profiles:
            f.write("- 未检测到 `PTO2_SCHED_PROFILE_JSON`（需要提供 `--log`，并确保运行时启用 profiling）。\n\n")
        else:
            f.write("| thread | cores | completed | total(us) | scan(us) | orch_drain(us) | complete(us) | dispatch(us) | yield(us) | ts_ok | ts_fail |\n")
            f.write("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
            for p in sorted(sched_profiles, key=lambda x: int(x.get("thread_idx", 0))):
                f.write(
                    f"| {int(p.get('thread_idx', 0))} | {int(p.get('core_num', 0))} | {int(p.get('completed_by_thread', 0))} | "
                    f"{float(p.get('total_us', 0.0)):.3f} | {float(p.get('scan_us', 0.0)):.3f} | "
                    f"{float(p.get('orch_drain_us', 0.0)):.3f} | {float(p.get('complete_us', 0.0)):.3f} | "
                    f"{float(p.get('dispatch_us', 0.0)):.3f} | {float(p.get('yield_us', 0.0)):.3f} | "
                    f"{int(p.get('perf_ts_update_ok', 0))} | {int(p.get('perf_ts_update_fail', 0))} |\n"
                )
            f.write("\n")

            if sched_sum is not None:
                total_us = float(sched_sum.get("total_us", 0.0))
                completed = int(sched_sum.get("completed_by_thread", 0))
                us_per_task = (total_us / completed) if completed > 0 else 0.0
                f.write(
                    f"- 汇总：threads={sched_sum.get('threads')}, completed={completed}, total={total_us:.3f}us, "
                    f"avg_sched_loop_cost_per_completed_task≈{us_per_task:.3f}us\n"
                )
                f.write(
                    f"- 汇总 fanout：total_traversed={int(sched_sum.get('fanout_total_traversed', 0))}, "
                    f"max_len={int(sched_sum.get('fanout_max_len', 0))}\n"
                )
                f.write(
                    f"- PerfRecord 时间戳写入：ok={int(sched_sum.get('perf_ts_update_ok', 0))}, "
                    f"fail={int(sched_sum.get('perf_ts_update_fail', 0))}\n"
                )

                phases = [
                    ("scan", float(sched_sum.get("scan_us", 0.0))),
                    ("orch_drain", float(sched_sum.get("orch_drain_us", 0.0))),
                    ("complete", float(sched_sum.get("complete_us", 0.0))),
                    ("dispatch", float(sched_sum.get("dispatch_us", 0.0))),
                    ("yield", float(sched_sum.get("yield_us", 0.0))),
                ]
                phases.sort(key=lambda x: x[1], reverse=True)

                if total_us > 0:
                    top_name, top_us = phases[0]
                    f.write(f"- 主导阶段：`{top_name}` {top_us:.3f}us（{top_us * 100.0 / total_us:.1f}%）\n")

                f.write("\n### 阶段耗时占比排序（汇总）\n\n")
                f.write("| phase | time(us) | share |\n")
                f.write("|---|---:|---:|\n")
                for name, us in phases:
                    f.write(_phase_ranking_row(name, us, total_us) + "\n")
                f.write("\n")

        f.write("## 4) Schedule outliers（finish-dispatch 最大的任务）\n\n")
        if not outliers:
            f.write("- n/a\n\n")
        else:
            f.write("| rank | task_id | func | core | exec(us) | head(us) | tail(us) | schedule(us) |\n")
            f.write("|---:|---:|---|---:|---:|---:|---:|---:|\n")
            for i, t in enumerate(outliers, 1):
                f.write(
                    f"| {i} | {t.task_id} | {_func_name(t.func_id, func_map)}({t.func_id}) | {t.core_id} | "
                    f"{t.exec_us:.3f} | {_fmt_us(t.head_overhead_us)} | {_fmt_us(t.tail_overhead_us)} | "
                    f"{_fmt_us(t.schedule_us)} |\n"
                )
            f.write("\n")

        f.write("## 5) 优化空间（结合当前数据看优先级）\n\n")
        # Data-driven prioritization using per-task timeline when available.
        if sched_us_sum > 0:
            tail_share = tail_us_sum * 100.0 / sched_us_sum
            head_share = head_us_sum * 100.0 / sched_us_sum
            exec_share = exec_us_sum * 100.0 / sched_us_sum
            f.write(f"- 当前 run 的调度窗口占比：tail={tail_share:.1f}%, exec={exec_share:.1f}%, head={head_share:.1f}%\n")
            if tail_share >= 50.0:
                f.write("  - 最高优先级：降低 Tail（`end→finish`）= 完成观测延迟（AICPU completion detection / poll 频率 / 可见性）。\n")
            elif head_share >= 30.0:
                f.write("  - 最高优先级：降低 Head（`dispatch→start`）= 派发路径延迟（payload 构建/写寄存器/锁竞争）。\n")
            else:
                f.write("  - 最高优先级：按阶段占比排序优化。\n")
        else:
            f.write("- 缺少 dispatch/finish 时间戳时：优先补齐 AICPU dispatch/finish 记录再做定量排序。\n")

        f.write("\n### 详细优化清单（建议按优先级执行）\n\n")
        f.write("1. **降低 Tail（完成观测延迟）**\n")
        f.write("   - 将 `COND` 轮询改为更低开销/更低延迟方式：减少每轮读取寄存器次数，或者用批量读取/分组轮询。\n")
        f.write("   - 避免空转 `yield`：当无进展时做指数退避（spin → pause → yield），并在有 in-flight task 时提高完成检测频率。\n")
        f.write("   - 完成信号从寄存器改为共享内存队列/bitmap（AICore 完成写入 GM 中的 per-core flag，AICPU 扫描 cache-friendly bitmap）。\n")
        f.write("   - 在 AICPU 侧维护 `busy_core_list`（只轮询 busy cores，而不是每轮扫满 `core_num`）。\n")
        f.write("\n2. **降低 Head（派发延迟）**\n")
        f.write("   - `ready_queue_*_lock_`：改为 per-thread queue 或无锁 ring（减少多 scheduler 线程竞争）。\n")
        f.write("   - `build_pto2_payload`：缓存常用参数布局/减少分支；必要时把 payload 预生成到 task descriptor（dispatch 只做 memcpy）。\n")
        f.write("   - 减少寄存器写次数：合并写，或避免重复写 `FAST_PATH_ENABLE`/`DATA_MAIN_BASE` 相关状态。\n")
        f.write("\n3. **降低 Complete（依赖推进成本）**\n")
        f.write("   - fanout 遍历：压缩 dep list、改善局部性；避免频繁原子（例如按块累加再提交）。\n")
        f.write("   - `fanout_lock`：缩短持锁区（现在已将遍历移出锁，继续检查是否还能避免锁或用更轻量原语）。\n")
        f.write("\n4. **降低 Scan / orch_drain（就绪发现成本）**\n")
        f.write("   - `next_scan_index_` 的 CAS 争用：改为按 chunk 分配（一次 claim N 个 index）降低原子频率。\n")
        f.write("   - orchestrator ready queue：如果 drain 占比高，考虑批量 drain + per-thread local buffer。\n")
        f.write("\n5. **降低 profiling 引入的扰动**\n")
        f.write("   - 若开启更细粒度调度 profiling 导致延时波动大：降低采样频率（例如只统计每 2^k 个 loop），并按采样倍率缩放。\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PTO2 scheduling report (Markdown)")
    parser.add_argument(
        "perf",
        nargs="?",
        help="perf_swimlane_*.json path (default: latest in outputs/)",
    )
    parser.add_argument(
        "-k",
        "--kernel-config",
        default=None,
        help="kernel_config.py (optional, for func_id->name mapping)",
    )
    parser.add_argument(
        "--log",
        default=None,
        help="log file path containing PTO2_SCHED_PROFILE_JSON lines (optional)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="output Markdown path (default: outputs/pto2_schedule_report_<timestamp>.md)",
    )

    args = parser.parse_args()

    perf_path = Path(args.perf) if args.perf else _find_latest_outputs_file("perf_swimlane_*.json")
    perf = _load_json(perf_path)
    tasks = _parse_tasks(perf)

    func_map = _load_kernel_config_mapping(Path(args.kernel_config) if args.kernel_config else None)

    log_path = Path(args.log) if args.log else None
    sched_profiles: List[Dict[str, Any]] = []
    # Prefer scheduler profiles embedded in perf_swimlane JSON (works on real hardware).
    embedded = perf.get("scheduler_profiles")
    if isinstance(embedded, list) and embedded:
        sched_profiles = [p for p in embedded if isinstance(p, dict)]
    elif log_path is not None:
        profiles_with_lineno = _parse_scheduler_profiles_with_lineno(log_path)
        sched_profiles = _pick_last_run_profiles(profiles_with_lineno, log_path, perf_path.name)

    if args.output:
        out_path = Path(args.output)
    else:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = Path("outputs") / f"pto2_schedule_report_{ts}.md"

    _write_report(
        out_path=out_path,
        perf_path=perf_path,
        tasks=tasks,
        func_map=func_map,
        log_path=log_path,
        sched_profiles=sched_profiles,
    )
    print(f"[OK] Wrote report: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
